from __future__ import annotations


FEATURE_DETAILS = {
    "barbaro": [
        (1, "Fúria", "Em combate, você pode entrar em fúria como ação bônus. Enquanto não usar armadura pesada, recebe bônus no dano de ataques corpo a corpo com Força, vantagem em testes e resistências de Força, e resistência a dano contundente, cortante e perfurante. A fúria termina se você ficar inconsciente ou passar um turno sem atacar uma criatura hostil nem sofrer dano."),
        (1, "Defesa sem Armadura", "Sem armadura, sua CA é 10 + modificador de Destreza + modificador de Constituição. Você pode usar escudo e manter esse cálculo."),
        (2, "Ataque Imprudente", "No primeiro ataque do turno, você pode ganhar vantagem em ataques corpo a corpo com Força. Até seu próximo turno, ataques contra você também têm vantagem."),
        (2, "Sentido de Perigo", "Você tem vantagem em testes de resistência de Destreza contra efeitos que possa ver, como armadilhas e magias. Não funciona se estiver cego, surdo ou incapacitado."),
        (3, "Caminho Primitivo", "Escolha uma subclasse de bárbaro. Ela concede características no 3º, 6º, 10º e 14º níveis."),
        (5, "Ataque Extra", "Quando usa a ação Atacar no seu turno, você ataca duas vezes."),
        (5, "Movimento Rápido", "Seu deslocamento aumenta em 3 metros enquanto não estiver usando armadura pesada."),
        (7, "Instinto Selvagem", "Você tem vantagem em iniciativa. Se for surpreendido, pode agir no primeiro turno se entrar em fúria antes de fazer qualquer outra coisa."),
        (9, "Crítico Brutal", "Ao acertar crítico com ataque corpo a corpo, role um dado de dano extra da arma. Esse bônus aumenta em níveis posteriores."),
        (11, "Fúria Implacável", "Se cair a 0 PV durante a fúria e não morrer imediatamente, faça resistência de Constituição CD 10 para cair a 1 PV. A CD aumenta em 5 a cada uso até descanso curto ou longo."),
        (15, "Fúria Persistente", "Sua fúria só termina antes do tempo se você cair inconsciente ou decidir encerrá-la."),
        (18, "Poder Indomável", "Se seu teste de Força for menor que seu valor de Força, use o valor de Força como resultado."),
        (20, "Campeão Primitivo", "Força e Constituição aumentam em 4, e seus máximos desses atributos também aumentam em 4."),
    ],
    "bardo": [
        (1, "Conjuração", "Você lança magias de bardo usando Carisma. Conhece truques e magias conforme a tabela da classe, e recupera espaços de magia em descanso longo."),
        (1, "Inspiração de Bardo", "Como ação bônus, escolha uma criatura a até 18 m que possa ouvi-lo. Ela ganha um dado de inspiração para somar a um teste, ataque ou resistência nos próximos 10 minutos. O dado cresce com o nível."),
        (2, "Versatilidade", "Você adiciona metade do bônus de proficiência, arredondado para baixo, a testes de atributo nos quais ainda não aplica proficiência."),
        (2, "Canção de Descanso", "Durante descanso curto, aliados que gastarem Dados de Vida recuperam PV adicionais conforme seu dado de bardo."),
        (3, "Colégio de Bardo", "Escolha uma subclasse de bardo. Ela concede características no 3º, 6º e 14º níveis."),
        (3, "Especialização", "Escolha duas proficiências em perícia. Seu bônus de proficiência dobra nelas. Mais duas são escolhidas no 10º nível."),
        (5, "Fonte de Inspiração", "Você recupera usos de Inspiração de Bardo ao terminar descanso curto ou longo."),
        (6, "Contra-encantamento", "Como ação, até o fim do seu próximo turno, você e aliados a até 9 m têm vantagem contra efeitos de medo e encantamento enquanto puderem ouvi-lo."),
        (10, "Segredos Mágicos", "Aprenda magias de qualquer classe. Elas contam como magias de bardo para você. Você ganha novas escolhas em níveis posteriores."),
        (20, "Inspiração Superior", "Ao rolar iniciativa sem usos de Inspiração de Bardo, recupera um uso."),
    ],
    "bruxo": [
        (1, "Patrono Transcendental", "Escolha o patrono que concede seu pacto. Ele define magias expandidas e características no 1º, 6º, 10º e 14º níveis."),
        (1, "Magia de Pacto", "Você lança magias de bruxo usando Carisma. Seus espaços são poucos, mas todos têm o mesmo nível indicado na tabela e retornam em descanso curto ou longo."),
        (2, "Invocações Místicas", "Escolha invocações que modificam magias, sentidos ou capacidades. Você aprende mais conforme sobe de nível e pode trocar algumas ao evoluir."),
        (3, "Dádiva do Pacto", "Escolha Corrente, Lâmina ou Tomo, ganhando familiar especial, arma de pacto ou truques adicionais."),
        (11, "Arcana Mística", "Você aprende uma magia de 6º nível que pode lançar uma vez por descanso longo sem gastar espaço. Níveis maiores concedem arcanas de 7º, 8º e 9º níveis."),
        (20, "Mestre Místico", "Após 1 minuto suplicando ao patrono, recupera todos os espaços de Magia de Pacto gastos. Use uma vez por descanso longo."),
    ],
    "clerigo": [
        (1, "Conjuração", "Você prepara magias de clérigo usando Sabedoria. Pode trocar magias preparadas ao terminar descanso longo e usa foco sagrado."),
        (1, "Domínio Divino", "Escolha um domínio. Ele concede magias sempre preparadas e características de domínio no 1º, 2º, 6º, 8º e 17º níveis."),
        (2, "Canalizar Divindade", "Use uma ação para liberar energia divina. Todo clérigo pode Expulsar Mortos-vivos; o domínio acrescenta opções. Usos aumentam com o nível e retornam em descanso curto ou longo."),
        (5, "Destruir Mortos-vivos", "Quando um morto-vivo falha contra Expulsar Mortos-vivos, ele é destruído se seu ND for baixo o bastante para seu nível."),
        (10, "Intervenção Divina", "Peça ajuda direta da divindade. Role d100; se o resultado for igual ou menor que seu nível de clérigo, o Mestre determina a intervenção. No 20º nível, funciona automaticamente."),
    ],
    "druida": [
        (1, "Druídico", "Você conhece o idioma secreto dos druidas e pode deixar mensagens ocultas para outros druidas."),
        (1, "Conjuração", "Você prepara magias de druida usando Sabedoria. Pode trocar magias preparadas ao terminar descanso longo e usa foco druídico."),
        (2, "Forma Selvagem", "Como ação, assuma forma de besta vista antes. O ND máximo e limitações de natação/voo melhoram com o nível. Você mantém mente e proficiências, usa estatísticas físicas da besta e retorna ao cair a 0 PV da forma."),
        (2, "Círculo Druídico", "Escolha uma subclasse de druida. Ela concede características no 2º, 6º, 10º e 14º níveis."),
        (18, "Corpo Atemporal", "Para cada 10 anos passados, seu corpo envelhece apenas 1 ano."),
        (18, "Magias Bestiais", "Você pode conjurar magias de druida em Forma Selvagem, ignorando componentes verbais e somáticos, mas ainda precisa de componentes materiais caros ou consumidos."),
        (20, "Arquedruida", "Você pode usar Forma Selvagem ilimitadamente e ignora componentes verbais, somáticos e materiais sem custo/consumo em forma normal ou selvagem."),
    ],
    "feiticeiro": [
        (1, "Conjuração", "Você lança magias de feiticeiro usando Carisma. Conhece magias em vez de preparar, e troca uma magia conhecida ao subir de nível."),
        (1, "Origem Feiticeira", "Escolha a origem de sua magia. Ela concede características no 1º, 6º, 14º e 18º níveis."),
        (2, "Fonte de Magia", "Você ganha pontos de feitiçaria. Pode convertê-los em espaços de magia e converter espaços em pontos."),
        (3, "Metamagia", "Escolha opções que modificam magias ao conjurá-las, como aumentar alcance, afetar outro alvo, acelerar conjuração ou dificultar resistência. Gasta pontos de feitiçaria."),
        (20, "Restauração Mística", "Ao terminar descanso curto, recupera 4 pontos de feitiçaria se estiver com 0."),
    ],
    "guerreiro": [
        (1, "Estilo de Luta", "Escolha uma especialização marcial, como Arquearia, Defesa, Duelo, Proteção ou combate com duas armas."),
        (1, "Retomar o Fôlego", "Como ação bônus, recupere 1d10 + nível de guerreiro PV. Use uma vez por descanso curto ou longo."),
        (2, "Surto de Ação", "No seu turno, ganhe uma ação adicional além da ação normal e possível ação bônus. Recupera em descanso curto ou longo; ganha mais usos em níveis altos."),
        (3, "Arquétipo Marcial", "Escolha uma subclasse de guerreiro. Ela concede características no 3º, 7º, 10º, 15º e 18º níveis."),
        (5, "Ataque Extra", "Quando usa a ação Atacar, faz ataques adicionais conforme a progressão da classe."),
        (9, "Indomável", "Repita um teste de resistência que falhou. Recupera em descanso longo; ganha mais usos em níveis altos."),
    ],
    "ladino": [
        (1, "Especialização", "Escolha duas proficiências em perícia ou uma perícia e ferramentas de ladrão. Seu bônus dobra nelas. Mais escolhas no 6º nível."),
        (1, "Ataque Furtivo", "Uma vez por turno, cause dano extra se tiver vantagem no ataque ou se um aliado ameaçar o alvo. Requer arma de acuidade ou à distância."),
        (1, "Gíria de Ladrão", "Você entende códigos, sinais e expressões secretas usados por criminosos e contatos do submundo."),
        (2, "Ação Ardilosa", "Como ação bônus, pode Disparada, Desengajar ou Esconder-se."),
        (3, "Arquétipo de Ladino", "Escolha uma subclasse de ladino. Ela concede características no 3º, 9º, 13º e 17º níveis."),
        (5, "Esquiva Sobrenatural", "Use reação para reduzir pela metade o dano de um ataque que possa ver."),
        (7, "Evasão", "Em resistência de Destreza contra metade do dano, sofre 0 em sucesso e metade em falha."),
        (11, "Talento Confiável", "Em testes com proficiência, resultados de d20 menores que 10 contam como 10."),
        (14, "Sentido Cego", "Se puder ouvir, sabe a localização de criaturas escondidas ou invisíveis a até 3 m."),
        (15, "Mente Escorregadia", "Ganha proficiência em testes de resistência de Sabedoria."),
        (18, "Elusivo", "Nenhum ataque contra você tem vantagem enquanto você não estiver incapacitado."),
        (20, "Golpe de Sorte", "Transforme um ataque falho em acerto ou um teste falho em 20. Use uma vez por descanso curto ou longo."),
    ],
    "mago": [
        (1, "Conjuração", "Você prepara magias de mago a partir do grimório usando Inteligência. Pode copiar magias para o grimório e conjurar rituais nele."),
        (1, "Recuperação Arcana", "Uma vez por dia após descanso curto, recupere espaços de magia com soma de níveis até metade do nível de mago arredondada para cima."),
        (2, "Tradição Arcana", "Escolha uma escola ou tradição. Ela concede características no 2º, 6º, 10º e 14º níveis."),
        (18, "Domínio de Magia", "Escolha uma magia de 1º e uma de 2º nível no grimório. Pode lançá-las no menor nível sem gastar espaço quando preparadas."),
        (20, "Magias Assinatura", "Escolha duas magias de 3º nível preparadas. Pode lançar cada uma uma vez por descanso curto ou longo sem gastar espaço."),
    ],
    "monge": [
        (1, "Defesa sem Armadura", "Sem armadura nem escudo, sua CA é 10 + Destreza + Sabedoria."),
        (1, "Artes Marciais", "Sem armadura nem escudo, pode usar Destreza para ataques com armas de monge e golpes desarmados, usar dado marcial e fazer golpe desarmado como ação bônus após atacar."),
        (2, "Ki", "Você ganha pontos de ki, recuperados em descanso curto ou longo. Pode usar Rajada de Golpes, Defesa Paciente e Passo do Vento."),
        (2, "Movimento sem Armadura", "Seu deslocamento aumenta sem armadura nem escudo; em níveis altos, permite correr por superfícies verticais e água durante o movimento."),
        (3, "Tradição Monástica", "Escolha uma subclasse de monge. Ela concede características no 3º, 6º, 11º e 17º níveis."),
        (3, "Defletir Mísseis", "Use reação para reduzir dano de ataque à distância com arma. Se reduzir a 0, pode gastar ki para arremessar o projétil de volta."),
        (4, "Queda Lenta", "Use reação ao cair para reduzir dano de queda em 5 vezes seu nível de monge."),
        (5, "Ataque Extra", "Quando usa a ação Atacar, ataca duas vezes."),
        (5, "Ataque Atordoante", "Ao acertar ataque corpo a corpo com arma, gaste ki para forçar resistência de Constituição. Falha deixa o alvo atordoado até o fim do seu próximo turno."),
        (6, "Golpes de Ki", "Seus golpes desarmados contam como mágicos para superar resistência e imunidade a ataques não mágicos."),
        (7, "Evasão", "Em resistência de Destreza contra metade do dano, sofre 0 em sucesso e metade em falha."),
        (7, "Mente Tranquila", "Use ação para encerrar um efeito que esteja causando medo ou encantamento em você."),
        (10, "Pureza Corporal", "Torna-se imune a doenças e venenos."),
        (13, "Idioma do Sol e da Lua", "Você entende todos os idiomas falados, e qualquer criatura que conheça idioma entende sua fala."),
        (14, "Alma de Diamante", "Ganha proficiência em todos os testes de resistência e pode gastar ki para repetir uma falha."),
        (15, "Corpo Atemporal", "Não sofre fragilidade da velhice, não pode ser envelhecido magicamente e não precisa de comida ou água."),
        (18, "Corpo Vazio", "Gaste ki para ficar invisível e resistente a quase todo dano por 1 minuto, ou para conjurar projeção astral em si."),
        (20, "Autoperfeição", "Ao rolar iniciativa com menos de 4 ki, fica com 4 ki."),
    ],
    "paladino": [
        (1, "Sentido Divino", "Como ação, detecte celestiais, corruptores e mortos-vivos a até 18 m que não estejam atrás de cobertura total, além de locais ou objetos consagrados/profanados. Usos por descanso longo são 1 + Carisma."),
        (1, "Cura pelas Mãos", "Você tem uma reserva de cura igual a 5 x nível de paladino. Como ação, toque uma criatura para curar PV ou gastar 5 pontos para remover uma doença ou veneno."),
        (2, "Estilo de Luta", "Escolha uma especialização marcial, como Defesa, Duelo, Luta com Arma Grande ou Proteção."),
        (2, "Conjuração", "Você prepara magias de paladino usando Carisma, com acesso a foco sagrado e espaços conforme a tabela."),
        (2, "Destruição Divina", "Ao acertar ataque corpo a corpo com arma, gaste espaço de magia para causar dano radiante extra. Dano aumenta com o nível do espaço e é maior contra corruptores e mortos-vivos."),
        (3, "Saúde Divina", "Você se torna imune a doenças."),
        (3, "Juramento Sagrado", "Escolha uma subclasse de paladino. Ela concede magias de juramento e características no 3º, 7º, 15º e 20º níveis."),
        (6, "Aura de Proteção", "Você e aliados a até 3 m somam seu modificador de Carisma a testes de resistência. O alcance aumenta em níveis altos."),
        (10, "Aura de Coragem", "Você e aliados a até 3 m não podem ser amedrontados enquanto você estiver consciente. O alcance aumenta em níveis altos."),
        (11, "Destruição Divina Aprimorada", "Seus ataques corpo a corpo com arma causam dano radiante adicional."),
        (14, "Toque Purificador", "Como ação, toque uma criatura para encerrar uma magia nela ou em você. Usos por descanso longo iguais ao modificador de Carisma."),
    ],
    "patrulheiro": [
        (1, "Inimigo Favorito", "Escolha tipos de criatura como inimigos favoritos. Você tem vantagem para rastreá-los e para lembrar informações sobre eles, além de aprender um idioma associado se aplicável."),
        (1, "Explorador Natural", "Escolha terreno favorito. Ao viajar por 1 hora ou mais nele, terreno difícil não atrasa o grupo, o grupo não se perde por meios não mágicos, você permanece alerta enquanto viaja e melhora forrageamento/rastreamento."),
        (2, "Estilo de Luta", "Escolha uma especialização marcial, como Arquearia, Defesa, Duelo ou combate com duas armas."),
        (2, "Conjuração", "Você aprende e lança magias de patrulheiro usando Sabedoria. Conhece magias conforme a tabela e recupera espaços em descanso longo."),
        (3, "Arquétipo de Patrulheiro", "Escolha uma subclasse de patrulheiro. Ela concede características no 3º, 7º, 11º e 15º níveis."),
        (3, "Consciência Primitiva", "Gaste espaço de magia para sentir se certos tipos de criatura estão a até 1,5 km, ou 9 km em terreno favorito. Não revela quantidade ou localização."),
        (5, "Ataque Extra", "Quando usa a ação Atacar, ataca duas vezes."),
        (8, "Passo da Terra", "Mover-se por terreno difícil não mágico custa movimento normal. Você tem vantagem contra plantas criadas/manipuladas magicamente para impedir movimento."),
        (10, "Esconder-se à Plena Vista", "Com 1 minuto de preparação, crie camuflagem em terreno natural. Enquanto ficar parado sem ações, ganha bônus alto em Furtividade."),
        (14, "Desaparecer", "Pode Esconder-se como ação bônus e não pode ser rastreado por meios não mágicos a menos que queira."),
        (18, "Sentidos Selvagens", "Atacar criaturas que você não vê não impõe desvantagem por esse motivo. Também percebe criaturas invisíveis próximas se não estiverem escondidas."),
        (20, "Matador de Inimigos", "Uma vez por turno, some Sabedoria a ataque ou dano contra inimigo favorito. Pode decidir após rolar, antes do resultado."),
    ],
}


SUBCLASS_DETAILS = {
    "Caminho do Berserker": "3º: Frenesi permite ataque extra como ação bônus durante fúria, mas causa exaustão ao final. 6º: fica imune a medo e encantamento durante fúria. 10º: usa ação para amedrontar uma criatura. 14º: reage a dano corpo a corpo atacando o agressor.",
    "Caminho do Totem": "3º: escolha espírito totêmico como urso, águia ou lobo para alterar a fúria. 6º: ganha benefício exploratório do totem. 10º: consulta espiritualmente a natureza. 14º: ganha efeito de combate avançado do totem escolhido.",
    "Colégio do Conhecimento": "3º: ganha perícias adicionais e pode reduzir ataques/testes/dano de inimigos com Palavras de Interrupção. 6º: aprende magias de qualquer lista. 14º: pode inspirar a si mesmo em testes.",
    "Colégio da Bravura": "3º: ganha armaduras, escudos e armas marciais; inspiração pode aumentar dano ou CA. 6º: ganha Ataque Extra. 14º: após conjurar magia de bardo, pode atacar como ação bônus.",
    "Domínio do Conhecimento": "Ganha magias de conhecimento, perícias/idiomas, Canalizar Divindade para proficiência temporária ou leitura de pensamentos, e poderes de visão do passado em níveis altos.",
    "Domínio da Enganação": "Ganha magias de ilusão e infiltração, concede vantagem em Furtividade, cria duplicata ilusória, torna-se invisível por Canalizar Divindade e melhora duplicatas em níveis altos.",
    "Domínio da Guerra": "Ganha proficiências marciais, ataques extras por ação bônus, Canalizar Divindade para bônus em ataques, melhora ataques de aliados e adiciona dano divino em níveis altos.",
    "Domínio da Luz": "Ganha truque de luz, impõe desvantagem a ataques com clarão, usa Canalizar Divindade para dissipar trevas e causar dano radiante, e amplia dano/defesa luminosa.",
    "Domínio da Natureza": "Ganha truque druídico, proficiência ou armadura pesada, Canalizar Divindade para encantar animais/plantas, resistência elemental e comando de criaturas naturais.",
    "Domínio da Tempestade": "Ganha armas/armaduras, pune atacantes com trovão/relâmpago, maximiza dano elétrico/trovejante com Canalizar Divindade, empurra inimigos e ganha voo em níveis altos.",
    "Domínio da Vida": "Fortalece curas, Canalizar Divindade distribui cura em área, cura a si mesmo ao curar outros, melhora magias de cura e maximiza dados de cura em níveis altos.",
    "Círculo da Terra": "Recupera magia em descanso curto, ganha magias de círculo por terreno, ignora certos terrenos difíceis, resiste a encantos/medo de elementais e fadas, e dificulta ataques de criaturas naturais.",
    "Círculo da Lua": "Usa Forma Selvagem como ação bônus, acessa bestas mais fortes, gasta magia para curar na forma, ataques da forma contam como mágicos e pode assumir formas elementais.",
    "Linhagem Dracônica": "Ganha PV e armadura natural, afinidade elemental com dano/resistência, asas em nível alto e presença dracônica para amedrontar ou encantar.",
    "Magia Selvagem": "Pode gerar surtos de magia selvagem, manipular sorte com Marés do Caos, alterar rolagens com pontos de feitiçaria e melhorar controle dos surtos em níveis altos.",
    "Campeão": "Aumenta margem de crítico, melhora testes físicos, ganha estilo de luta adicional e regenera PV quando está muito ferido em níveis altos.",
    "Mestre de Batalha": "Ganha dados de superioridade e manobras para empurrar, derrubar, comandar, aparar ou controlar ataques. Dados aumentam e retornam em descanso curto ou longo.",
    "Cavaleiro Místico": "Aprende magias de mago, vincula armas, combina ataque e magia, impõe desvantagem contra suas magias e teleporta com Surto de Ação em níveis altos.",
    "Assassino": "Ganha proficiências de infiltração, vantagem contra alvos que ainda não agiram, críticos contra surpresos, identidades falsas e dano devastador contra alvos surpreendidos.",
    "Ladrão": "Usa objetos e ferramentas com ação bônus, escala e salta melhor, infiltra itens mágicos sem restrições comuns, age rapidamente em emboscadas e ganha turno extra inicial.",
    "Trapaceiro Arcano": "Aprende magia de mago focada em ilusão/encantamento, usa Mãos Mágicas para truques furtivos, embosca com magia e pode roubar controle mágico em níveis altos.",
    "Escola de Abjuração": "Copia abjurações mais barato, cria proteção arcana que absorve dano, protege aliados com a barreira e ganha resistência contra magias.",
    "Escola de Adivinhação": "Copia adivinhações mais barato, substitui rolagens com presságios, recupera espaços ao lançar adivinhações e amplia percepção especial.",
    "Escola de Conjuração": "Copia conjurações mais barato, cria objetos menores, teleporta, mantém concentração em conjurações e fortalece criaturas invocadas.",
    "Escola de Encantamento": "Copia encantamentos mais barato, hipnotiza criatura próxima, redireciona ataques, afeta múltiplos alvos e apaga memória de encantamentos.",
    "Escola de Evocação": "Copia evocações mais barato, protege aliados de suas áreas, melhora truques, adiciona Inteligência ao dano e maximiza magia com risco.",
    "Escola de Ilusão": "Copia ilusões mais barato, melhora Ilusão Menor, altera ilusões existentes, cria duplicata defensiva e torna parte da ilusão real por curto período.",
    "Escola de Necromancia": "Copia necromancias mais barato, recupera PV ao matar com magias, cria mortos-vivos melhores, resiste a necrose e controla mortos-vivos alheios.",
    "Escola de Transmutação": "Copia transmutações mais barato, altera materiais, cria pedra transmutadora com benefícios, muda de forma e consome a pedra para efeitos poderosos.",
    "Caminho da Mão Aberta": "Rajada de Golpes pode derrubar, empurrar ou impedir reações. Depois ganha cura própria, tranquilidade defensiva e técnica final vibratória.",
    "Caminho das Sombras": "Ganha magias de sombra com ki, teleporta entre áreas escuras, fica invisível em penumbra/escuridão e reage atacando inimigos atingidos por aliados.",
    "Caminho dos Quatro Elementos": "Escolhe disciplinas elementais que gastam ki para produzir efeitos como rajadas, controle de água/ar/fogo/terra e magias elementais.",
    "Juramento da Devoção": "Canaliza arma sagrada ou expulsa profanos, ganha aura contra encantamento, fica sempre sob proteção contra o mal e assume forma sagrada no ápice.",
    "Juramento dos Anciões": "Canaliza natureza para prender ou expulsar criaturas, concede resistência a dano de magia, evita cair a 0 PV uma vez e assume forma ancestral luminosa.",
    "Juramento da Vingança": "Canaliza para amedrontar ou marcar alvo com vantagem, persegue inimigos que fogem, reage a ataques e se torna vingador alado no ápice.",
    "Caçador": "Escolhe técnicas contra presas no 3º, defesa no 7º, multiataque no 11º e defesa superior no 15º. Opções incluem dano extra, ataques contra grupos e evasão.",
    "Mestre das Bestas": "Ganha companheiro animal que age com seus comandos. Conforme sobe de nível, o vínculo melhora ataques, defesas e coordenação entre patrulheiro e besta.",
    "O Arquifada": "Ganha presença feérica para encantar/amedrontar, teleporte evasivo, defesa contra encantamento e poder de mergulhar alvo em ilusão ou sonho sombrio.",
    "O Corruptor": "Ganha PV temporários ao derrotar inimigos, altera testes com favor sombrio, escolhe resistência após descanso e arremessa inimigos por experiência infernal.",
    "O Grande Antigo": "Ganha telepatia, defesa contra leitura mental, resistência psíquica/reflexão mental e capacidade de criar servo encantado em níveis altos.",
    "Caminho do Guardião Ancestral": "3º: durante fúria, o primeiro inimigo que você acerta tem desvantagem contra seus aliados e eles resistem ao dano dele. 6º: reduz dano sofrido por aliado próximo com reação. 10º: consulta espíritos para augúrio/clarividência. 14º: quando reduz dano com os espíritos, causa dano retaliatório.",
    "Caminho do Arauto da Tempestade": "3º: escolhe aura de deserto, mar ou tundra que ativa efeitos enquanto está em fúria. 6º: ganha resistência e adaptação ao ambiente escolhido. 10º: compartilha resistência com aliados próximos. 14º: sua aura ganha reação ofensiva ou controle conforme o ambiente.",
    "Caminho do Zelote": "3º: causa dano radiante/necrótico extra uma vez por turno e é mais fácil de reviver. 6º: pode repetir resistência falha durante fúria. 10º: inspira aliados com grito de batalha. 14º: continua lutando mesmo a 0 PV enquanto a fúria durar.",
    "Colégio do Glamour": "3º: usa inspiração para dar PV temporários e mover aliados; também encanta uma audiência após apresentação. 6º: comanda criatura encantada como ação bônus. 14º: assume majestade feérica que dificulta ataques contra você.",
    "Colégio das Espadas": "3º: ganha armaduras médias, cimitarras, estilo de luta e floreios que gastam inspiração para dano, defesa ou empurrão. 6º: ganha Ataque Extra. 14º: usa floreio básico sem gastar inspiração.",
    "Colégio dos Sussurros": "3º: gasta inspiração para dano psíquico e assusta alvos isolados com palavras. 6º: rouba sombra de humanoide morto para disfarce. 14º: chantageia magicamente uma criatura com medo e encanto.",
    "Domínio da Forja": "Ganha proficiências de forja, abençoa arma/armadura, cria item simples com Canalizar Divindade, ganha resistência a fogo e bônus com armadura pesada, e em níveis altos imunidade a fogo e resistência física em armadura pesada.",
    "Domínio do Túmulo": "Estabiliza e cura melhor alvos a 0 PV, detecta mortos-vivos, usa Canalizar Divindade para deixar alvo vulnerável ao próximo dano, cancela críticos contra aliados e captura energia de mortes próximas para curar.",
    "Círculo dos Sonhos": "Ganha reserva de dados para curar e dar PV temporários, cria refúgio durante descanso, teleporta aliados por caminhos feéricos e usa magia onírica para vigília ou viagem.",
    "Círculo do Pastor": "Fala com animais/espíritos, invoca totem espiritual com aura de suporte, fortalece criaturas convocadas, cura invocações e recebe proteção espiritual quando cai.",
    "Alma Divina": "Acessa magias de clérigo além das de feiticeiro, recebe magia bônus por afinidade, melhora testes falhos com favor divino, cura melhor, ganha asas e pode se recuperar quando muito ferido.",
    "Magia das Sombras": "Enxerga no escuro melhor, resiste a cair a 0 PV, conjura escuridão especial, invoca cão sombrio contra alvo, teleporta entre sombras e assume forma sombria resistente.",
    "Feitiçaria da Tempestade": "Move-se sem provocar após conjurar magia, causa dano de tempestade ao lançar magias elétricas/trovejantes, ganha resistência e controle climático, protege aliados e voa em rajadas em níveis altos.",
    "Arqueiro Arcano": "Aprende disparos arcanos com efeitos especiais, cria flechas mágicas, redireciona disparos errados e melhora dano/efeitos dos disparos em níveis altos.",
    "Cavaleiro": "Marca inimigos para proteger aliados, ganha proficiências sociais/montaria, aumenta resistência defensiva, segura linha com ataques de oportunidade melhores e pune quem ignora sua marca.",
    "Samurai": "Ganha proficiência social, usa Espírito Lutador para vantagem e PV temporários, melhora presença social, ganha ataque extra ao abrir mão de vantagem e continua agindo ao cair em níveis altos.",
    "Inquisitivo": "Detecta mentiras e detalhes ocultos, usa Intuição para ativar Ataque Furtivo sem vantagem, melhora investigação/percepção e explora fraquezas do alvo em níveis altos.",
    "Mentor": "Ganha disfarces, falsificação e idiomas; usa Ajuda como ação bônus à distância; manipula identidade social e redireciona ataques para outras criaturas em níveis altos.",
    "Batedor": "Reage para afastar-se de inimigos que terminam perto, ganha perícias de exploração, aumenta deslocamento, dá vantagem inicial ao grupo e pode furtivar duas vezes contra alvos diferentes.",
    "Espadachim": "Ganha mobilidade após atacar, ativa Ataque Furtivo em duelo, usa Carisma para iniciativa, provoca ou encanta inimigos e transforma falhas em novas tentativas em níveis altos.",
    "Magia de Guerra": "Reage para bônus de CA ou resistência, soma Inteligência à iniciativa, acumula energia ao dissipar/contramágica, melhora dano enquanto concentra e ganha defesa constante ao manter magia.",
    "Caminho do Mestre Bêbado": "Ganha proficiências performáticas, Rajada de Golpes aumenta deslocamento e desengaja, redireciona ataques errados, cancela desvantagem com ki e ataca vários inimigos em níveis altos.",
    "Caminho do Kensei": "Escolhe armas kensei, ganha defesa ao lutar com elas, melhora dano com ki, transforma armas em mágicas e rerrola ataques em níveis altos.",
    "Caminho da Alma Solar": "Dispara energia radiante à distância, conjura explosões radiantes com ki, cria aura luminosa ofensiva/defensiva e causa dano radiante a agressores em níveis altos.",
    "Juramento da Conquista": "Canaliza presença conquistadora ou acerto preciso, prende criaturas amedrontadas em aura, pune dano recebido e assume forma de conquistador resistente e agressivo.",
    "Juramento da Redenção": "Canaliza diplomacia ou retalia dano sem atacar, absorve dano de aliados, regenera-se quando ferido e torna-se avatar pacificador difícil de matar em níveis altos.",
    "Conclave do Andarilho do Horizonte": "Detecta portais, transforma dano em energia planar, teleporta antes de ataques, atravessa planos com magia defensiva e pode atacar vários alvos teleportando entre eles.",
    "Conclave do Exterminador de Monstros": "Analisa resistências/imunidades/vulnerabilidades, marca presa para dano extra, melhora resistências contra alvo marcado e interrompe magias/teleportes em níveis altos.",
    "Conclave do Perseguidor Sombrio": "Ganha magia temática, bônus de iniciativa, ataque extra e dano no primeiro turno, invisibilidade contra visão no escuro, resistência mental e ataque adicional ao errar.",
    "O Celestial": "Ganha truques e cura em dados, adiciona dano radiante/fogo, recebe resistência radiante e PV temporários para o grupo, e volta de 0 PV com explosão luminosa.",
    "A Lâmina Maldita": "Usa maldição para crítico ampliado, dano e cura ao derrubar alvo; usa Carisma com arma escolhida, cria espectro de inimigo morto, melhora defesa e espalha maldição em níveis altos.",
}
